<a href="https://colab.research.google.com/github/suruanush/Numpy/blob/main/Numpy_Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to the NumPy practice exercise!

Good luck, and happy coding!

## Import library
- Do not modify the given attributes. Execute the below code cells sequencially to get the data.

In [ ]:
import numpy as np

Q.1 Create a 5x5 array, with numbers ranging from 1-25 and save it in `matrix` variable.
(Use `matrix` variable till were ever mentioned.)

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Q.2 select the subset from `matrix`
```python
Expected output
[[12,13,14,15],
 [17,18,18,20],
 [22,23,24,25]]
```

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
subset_q2 = matrix[2:, 1:]
print(subset_q2)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Q.3 Select the value 20 from the `matrix`

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
value_20 = matrix[3, 4]
print(value_20)

20


Q.4 Select the below subset.(Use `matrix`)
```python
Expected output
[[2],
 [7],
 [12]]
```


In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
subset_q4 = matrix[:3, 1:2]
print(subset_q4)

[[ 2]
 [ 7]
 [12]]


Q.5 Select the below subset. (Use `matrix`)
```python
Expected output
[21,22,23,24,25]
```

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
subset_q5 = matrix[4, :]
print(subset_q5)

[21 22 23 24 25]


Q.6 Select the subset below (Use `matrix`)
```python
Expected output
[[16,17,18,19,20],
 [21,22,23,24,25]]
```



In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
subset_q6 = matrix[3:, :]
print(subset_q6)

[[16 17 18 19 20]
 [21 22 23 24 25]]


Q.7 Get the sum of all the values in `matrix`. (Expected Ans : 325)

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
sum_matrix = matrix.sum()
print(sum_matrix)

325


Q.8 Get the standard deviation of the values in `matrix`(Expected Ans : 7.211102551)

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
std_dev_matrix = matrix.std()
print("{:.9f}".format(std_dev_matrix))

7.211102551


Q.9 Get the sum of all the columns in `matrix`. (Expected Ans: array([55,60,65,70,75])

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
sum_columns = matrix.sum(axis=0)
print(sum_columns)

[55 60 65 70 75]


Q.10 Reverse a 1D array.

In [ ]:
array_to_reverse = np.arange(1, 11)
reversed_array = array_to_reverse[::-1]
print(reversed_array)

[10  9  8  7  6  5  4  3  2  1]


Q.11 Find indices of non-zero elements from [10,20,0,0,40,0]

In [ ]:
non_zero_indices = np.nonzero([10, 20, 0, 0, 40, 0])
print(non_zero_indices)

(array([0, 1, 4]),)


Q.12 Create a 10x10 array with 1 on the border and 0 inside.

In [ ]:
bordered_array = np.ones((10, 10))
bordered_array[1:-1, 1:-1] = 0
print(bordered_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q. 13 Create 5x5 array and fill it with the cheakerboard pattern.

In [ ]:
checkerboard_5x5 = np.zeros((5, 5))
checkerboard_5x5[::2, ::2] = 1
checkerboard_5x5[1::2, 1::2] = 1

print(checkerboard_5x5)

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


Q.14 Create a numpy array of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
excluded_array = np.linspace(0.1, 0.9, 10)
print(excluded_array)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


Q.15 Create the matrix as array_5x5 (0-25) and swap first two rows.

In [ ]:
array_5x5 = np.arange(25).reshape(5, 5)
array_5x5[[0, 1]] = array_5x5[[1, 0]]

print(array_5x5)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# End!